<h1 align="center"> <b>Data Mining and Data Warehousing Lab. </b></h1>

<center> <b>Basic Python ML Demonstration-1 </b> </center>
<center> <b>Dahrii Paul </b></center>
<center>    (17-10-2024) </center>

# 1). Python Introduction

## I). Argument

* _**function(arguments)**_
  <br> return value -> output</br>
* Input -> process -> output

In [1]:
print("hello world")

hello world


* **Function:** print()
* **Argument:** "hello world"
* Input to a function are called **arguments**

In [2]:
print(print("hello world"))

hello world
None


* **Innermost** is resolve first & then the outside
* Returning **'None'** does not mean that the function does nothing. It simply means that the function does not return any useful data, but it can still perform other actions.

In [8]:
print(type(print))

<class 'builtin_function_or_method'>


* **print** is a function object that is passed as an argument to **type()**
* **print(type(print))** prints the type of the **print** function.
* **print** is not an argument by itself—it’s a function object being passed as an argument to the **type()** function


## II) Method

In [9]:
x = "hello"
print(x.upper())

HELLO


* **Object:** x (which store the string "hello")
* **Method:** upper()
* **Argument:** none 


* **Example:** raj.fetch(ball)
* ***object.methods(argument)***
    * raj - object
    * fetch - method
    * ball - argument 
* Input to a function are called **arguments**
* Class-specific functions present inside the object are called **methods**
* A specific instance of a class is **object**

In [5]:
y=5
print(y.upper())

AttributeError: 'int' object has no attribute 'upper'

* **AttributeError:** means that the object doesn't have this method

## III). dir() _function_
* **dir():** returns all properties and methods of the specified object, without the values
* **Returns details of the object class**

In [10]:
# dir(): details of the object class
x = 5
print(dir(x))

['__abs__', '__add__', '__and__', '__bool__', '__ceil__', '__class__', '__delattr__', '__dir__', '__divmod__', '__doc__', '__eq__', '__float__', '__floor__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getnewargs__', '__gt__', '__hash__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__le__', '__lshift__', '__lt__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr__', '__rfloordiv__', '__rlshift__', '__rmod__', '__rmul__', '__ror__', '__round__', '__rpow__', '__rrshift__', '__rshift__', '__rsub__', '__rtruediv__', '__rxor__', '__setattr__', '__sizeof__', '__str__', '__sub__', '__subclasshook__', '__truediv__', '__trunc__', '__xor__', 'as_integer_ratio', 'bit_count', 'bit_length', 'conjugate', 'denominator', 'from_bytes', 'imag', 'numerator', 'real', 'to_bytes']


In [18]:
a = x.__add__(5)
b = x + 5
print(f'a: {a}')
print(f'b: {b}')

a: 10
b: 10


* '**+**' is same with '**__add__**'

## IV). Container object
* A container object is an object that contains other objects. Container objects provide a way to store and organize multiple objects, allowing you to access, iterate over, and manipulate them collectively.

In [19]:
train =[1,"string",5.0,-50, print]
print(train)

[1, 'string', 5.0, -50, <built-in function print>]


In [20]:
print(train[2])

5.0


In [21]:
print(train[2])
print(train.__getitem__(2))

5.0
5.0


In [11]:
train =["a","b","c","d"]
print(train)
print(type(train))

['a', 'b', 'c', 'd']
<class 'list'>


In [16]:
from numpy import array
array4=array([1,2,3,4])
list4 =[1,2,3,4]
print(f'array4: {array4}')
print(f'list4: {list4}')

list4.append(6)
print(f'append 6: {list4}')

array4: [1 2 3 4]
list4: [1, 2, 3, 4]
append 6: [1, 2, 3, 4, 6]


## V). Dictionaries
* dict class (Dictionaries)
* cannot expressed using int object
* item can be any object
* store info in a sequence
* key do not need to be int and instead can be str
* create using {} , to separate : key from value

In [17]:
a={"key":"value"}
print(a)
print(type(a))
print(a["key"])

{'key': 'value'}
<class 'dict'>
value


In [18]:
squareof ={1:1,2:4,3:9,4:16,5:25,6:21}
print(squareof[2])
print(type(squareof))

4
<class 'dict'>


In [19]:
a ={"key":"value","second":5.0}
print(a)
print(type(a))
print(a["second"])

{'key': 'value', 'second': 5.0}
<class 'dict'>
5.0


## VI). Traversing a list

In [20]:
numbers = ["one", "two", "three", "four", "five", "six", "seven", "eight", "nine", "ten"]
print(numbers[0])
print(numbers[1])
print(numbers[2])
print(numbers[3])
print(numbers[4])
print(numbers[5])
print(numbers[6])
print(numbers[7])
print(numbers[8])
print(numbers[9])

one
two
three
four
five
six
seven
eight
nine
ten


## VII). For loop

* An alternative way to travel through a list is provided by the for loop in Python. It works like this :

In [22]:
print(numbers)
for number in numbers: #variable in container
  print(number)

['one', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight', 'nine', 'ten']
one
two
three
four
five
six
seven
eight
nine
ten


In [30]:
numbers = [1,2,3,4,5,6]
print(numbers)

for number in numbers:
  print(number)

[1, 2, 3, 4, 5, 6]
1
2
3
4
5
6


In [3]:
a = [1,2,3]
b = [4,5,6]
biglist=[a,b]
print(a)
print(b)
print(biglist)

[1, 2, 3]
[4, 5, 6]
[[1, 2, 3], [4, 5, 6]]


In [6]:
for a1 in biglist:
  for item in a1:
    print(item)
    print("Second for loop has completed one round")
  print("Frist for loop has completed one round")

1
Second for loop has completed one round
2
Second for loop has completed one round
3
Second for loop has completed one round
Frist for loop has completed one round
4
Second for loop has completed one round
5
Second for loop has completed one round
6
Second for loop has completed one round
Frist for loop has completed one round


In [23]:
row1=[1,2,3]
row2=[4,5,6]

table =[row1, row2]

for arow in table:
  for eachitem in arow:
    print(eachitem)

1
2
3
4
5
6


## VII). [Numpy array](https://numpy.org/doc/stable/)
* **NumPy _(Numerical Python)_:** It provides support for large, multi-dimensional arrays and matrices, along with a collection of high-level mathematical functions to operate on
these arrays.
> **Key Features:**
  > * Efficient handling of large arrays and matrices.
  > * Mathematical functions for operations on arrays without writing loops.
  > * Tools for integrating C/C++ and Fortran code.


In [28]:
from numpy import array

row1=[1,2,3]
row2=[4,5,6]

table =[row1, row2]
table = array(table)
print(table)

for arow in table:
  for eachitem in arow:
    print(eachitem)

[[1 2 3]
 [4 5 6]]
1
2
3
4
5
6


In [27]:
print(table[0][1])

2


In [29]:
# for loop
somelist =[1,2,3,"aa"]
print(somelist[0])

for item_one_By_one in somelist:
  print("in loop, ", item_one_By_one)
  x="hello"
  print(x)

1
in loop,  1
hello
in loop,  2
hello
in loop,  3
hello
in loop,  aa
hello


### Array Operations

In [34]:
import numpy
array1 = numpy.array([1, 2, 3, 4])
print(f'array1: {array1}')

# Element-wise operations
squared = array1 ** 2
sum_of_elements = numpy.sum(array)
print("Squared Elements:", squared)
print("Sum of Elements:", sum_of_elements)

array1: [1 2 3 4]
Squared Elements: [ 1  4  9 16]
Sum of Elements: <built-in function array>


### Matrix

In [37]:
import numpy as np
# Creating two 2x2 matrices
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

# Matrix multiplication
result = np.dot(matrix1, matrix2)

print("Matrix 1:\n", matrix1)
print("Matrix 2:\n", matrix2)
print("Matrix Multiplication Result:\n", result)

Matrix 1:
 [[1 2]
 [3 4]]
Matrix 2:
 [[5 6]
 [7 8]]
Matrix Multiplication Result:
 [[19 22]
 [43 50]]


### Setting seeds for reproducibility

In [46]:
import numpy as np

random_data1 = np.random.randn(5)
print("Random Data1:", random_data1)

random_data2 = np.random.randn(5)
print("Random Data2:", random_data2)

# Setting the seed for reproducibility
np.random.seed(42)
random_data3 = np.random.randn(5)
print("Random Data3:", random_data3)
np.random.seed(42)
random_data4 = np.random.randn(5)
print("Random Data4:", random_data4)

Random Data1: [-0.23413696  1.57921282  0.76743473 -0.46947439  0.54256004]
Random Data2: [-0.46341769 -0.46572975  0.24196227 -1.91328024 -1.72491783]
Random Data3: [ 0.49671415 -0.1382643   0.64768854  1.52302986 -0.23415337]
Random Data4: [ 0.49671415 -0.1382643   0.64768854  1.52302986 -0.23415337]


## VII). [Pandas](https://pandas.pydata.org/docs/user_guide/index.html)
* **Pandas:** It provides data structures and operations for manipulating numerical tables and time series.
> **Key Features:**
    > * DataFrame object for data manipulation with labeled axes (rows and columns).
    > * Tools for reading and writing data between in-memory data structures and various file formats (CSV, Excel, SQL databases).
    > * Data alignment and handling of missing data.

### Create a data frame

In [64]:
import pandas as pd

# Creating a DataFrame from a dictionary
data = {
    'Name': ['A', 'B', 'C', 'D'],
    'Age': [25, 30, 35, 40],
    'Uni': ['HCU', 'PU', 'DU', 'JNU']
}

df = pd.DataFrame(data)
print(df)

  Name  Age  Uni
0    A   25  HCU
1    B   30   PU
2    C   35   DU
3    D   40  JNU


### Read files

In [56]:
data = pd.read_csv('iris_train.csv')
print(data.head())

   Iris versicolor  4.70  1.40
0  Iris versicolor   4.5   1.5
1  Iris versicolor   4.9   1.5
2  Iris versicolor   4.0   1.3
3  Iris versicolor   4.6   1.5
4  Iris versicolor   4.5   1.3


### Data selection

In [77]:
print(df)

# Selecting a single column
ages = df['Age']
print("\nAges:\n", ages)

  Name  Age  Uni  Age in 10 Years
0    A   25  HCU               35
1    B   30   PU               40
2    C   35   DU               45
3    D   40  JNU               50

Ages:
 0    25
1    30
2    35
3    40
Name: Age, dtype: int64


In [67]:
# Selecting multiple columns
name_city = df[['Name', 'Uni']]
print("Name and university:\n", name_city)

Name and university:
   Name  Uni
0    A  HCU
1    B   PU
2    C   DU
3    D  JNU


In [68]:
# Selecting rows by index
first_two_rows = df.iloc[:2]
print("First two rows:\n", first_two_rows)

First two rows:
   Name  Age  Uni
0    A   25  HCU
1    B   30   PU


In [69]:
# Selecting rows by condition
above_30 = df[df['Age'] > 30]
print("Rows where Age > 30:\n", above_30)

Rows where Age > 30:
   Name  Age  Uni
2    C   35   DU
3    D   40  JNU


In [70]:
# Adding a new column with calculated data
df['Age in 10 Years'] = df['Age'] + 10
print(df)

  Name  Age  Uni  Age in 10 Years
0    A   25  HCU               35
1    B   30   PU               40
2    C   35   DU               45
3    D   40  JNU               50


### Merging dataframes

In [76]:
# Creating two DataFrames
df1 = pd.DataFrame({'ID': [1, 2, 3], 'Name': ['Alice', 'Bob', 'Charlie']})
df2 = pd.DataFrame({'ID': [1, 2, 3], 'Score': [85, 90, 95]})
print(df1)
print('\n',df2)

# Merging on a common column (ID)
merged_df = pd.merge(df1, df2, on='ID')
print("\nMerged DataFrame:\n", merged_df)


   ID     Name
0   1    Alice
1   2      Bob
2   3  Charlie

    ID  Score
0   1     85
1   2     90
2   3     95

Merged DataFrame:
    ID     Name  Score
0   1    Alice     85
1   2      Bob     90
2   3  Charlie     95


## VIII). [Matplotlib](https://matplotlib.org/stable/gallery/index.html) / [Seaborn](https://seaborn.pydata.org/examples/index.html): 
* **Matplotlib/Seaborn:** Matplotlib is a comprehensive library for creating static, animated, and interactive visualizations in Python. Seaborn is built on top of Matplotlib and provides a high-level interface for drawing attractive and informative statistical graphics.
> **Key Features:**
    > * Support for various plot types: line plots, scatter plots, bar charts, histograms, etc.
    > * Customization options for labels, colors, and styles.
    > * Seamless integration with Pandas data structures.

## IX). [Scikit-learn](https://scikit-learn.org/stable/):
* **Scikit-learn:** Scikit-learn is a versatile machine learning library for Python. It provides simple and efficient tools for data mining and data analysis, built on top of NumPy,
SciPy, and Matplotlib.
> **Key Features:**
    > * Consistent API for various machine learning algorithms: classification,
regression, clustering, dimensionality reduction, etc.
    > * Tools for model selection, evaluation, and validation.
    > * Integration with other Python libraries like Pandas for data handling and Matplotlib/Seaborn for visualization.

## X). [TensorFlow](https://www.tensorflow.org/tutorials) / [PyTorch](https://pytorch.org/tutorials/):
* **TensorFlow/PyTorch:** TensorFlow and PyTorch are powerful open-source libraries for numerical
computation and large-scale machine learning. They are primarily used for building
and training deep learning models.
> **Key Features:**
    > * Computational graph abstraction for defining and running complex neural
network models.
    > * Support for automatic differentiation and gradient-based optimization.
    > * Flexible deployment across different platforms and devices (CPUs, GPUs,
TPUs).